const express = require('express');
const router = express.Router();
const storageMulter = require('../../helpers/storageMulter');
const multer = require('multer');
const upload = multer({storage: storageMulter()}); 
const controller = require('../../controllers/admin/my-account.controller');
router.get('/', controller.index);
router.get('/edit', controller.edit);
router.patch('/edit', upload.single('avatar'), controller.editPatch);
module.exports = router;
